### ISSUE TITLE
Continuous crashes at launch

### ISSUE THREAD

**Issue by vosmike** [Shufflepuck/SplashBuddy#108]
MacBook Air T2 (2018)
OS Version 10.14.1
SplashBuddy version 1.3.1 and 1.3.0.

SplashBuddy crashes on startup.
**Error in system.log**
Nov 14 14:28:24 MacBook-Air-van-Test SplashBuddy[2798]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Nov 14 14:28:25 MacBook-Air-van-Test com.apple.xpc.launchd[1] (io.fti.SplashBuddy.1972[2798]): Service exited due to SIGILL | sent by exc handler[2798]

**Crash Report**

[Crash Report.txt](https://github.com/Shufflepuck/SplashBuddy/files/2581090/Crash.Report.txt)

**Comment by vosmike** [comment]
Just did a third test, making sure the Dark Mode wasn’t causing it.. it doesn’t

**Comment by Ethenyl** [comment]
Hi @vosmike, are you starting the App with a specific configuration?

**Comment by vosmike** [comment]
What configuration are you referring to?
Hardware is as mentioned above. Other than that it's the usual install.
Package drops, SB gets installed and launches

**Comment by Ethenyl** [comment]
@vosmike would you be available to perform some live testing on a specific branch? I might have a clue on the issue, seems to be related to the user input feature.

**Comment by vosmike** [comment]
Definitely!

**Comment by cybertunnel** [comment]
I also added a branch `bugfix/Crash_Fix` Let me know if this fixes the issue you are having.

**Comment by Ethenyl** [comment]
Fixed in #109.
