### ISSUE TITLE
Issue with icons

### ISSUE THREAD

**Issue by entusdictus** [Shufflepuck/SplashBuddy#111]
There is a small light grey top/down bar on the left side of icons that nearly fit the 128x128px size. 

Example for the Symantec icon below:
![not selected](https://user-images.githubusercontent.com/14052665/51099253-f524a780-17cf-11e9-96a7-cd9a330d2def.png)

When selecting the affected step in SB, the light grey bar disappears:
![selected](https://user-images.githubusercontent.com/14052665/51099252-f48c1100-17cf-11e9-845e-b682b788fc4e.png)

As seen on the full list, almost all of the icons are affected. Yes, its hard to see, but please check Adobe Reader, Enterprise Connect and Symantec.

![full list](https://user-images.githubusercontent.com/14052665/51099400-b6dbb800-17d0-11e9-9be7-37880d4e2f6c.png)

The icons itself definitely doesn't contain that grey bar. Please check the example for Symantec below.

<img width="64" alt="symantecendpointprotection" src="https://user-images.githubusercontent.com/14052665/51099418-d5da4a00-17d0-11e9-9044-d1b2e2cad824.png">

**Comment by cybertunnel** [comment]
Seems like it was a overlay from the textfields. Added bigger trailing constraints on the textfields and seems to have gone away. Could you compile and confirm please.

**Comment by entusdictus** [comment]
Sorry @cybertunnel , but I have absolutely no knowledge in how to use Xcode or how to compile a product with changes...
