### ISSUE TITLE
SB beach balls when click Continue

### ISSUE THREAD

**Issue by davidyoondrums** [Shufflepuck/SplashBuddy#112]
I am using

<dict>
	<key>continueAction</key>
	<string>/Applications/Self Service.app</string>
	<key>applicationsArray</key>
	<array>

to launch Jamf Self Service upon clicking continue button. But occasionally SB beach balls, and the only thing I can do is to force restart the computer. It doesn't happen all the time. I can see Self Service launching in the translucent SB background so I know Self Service app is launching in the background but SB seems to hang hard while trying to terminate itself after launching the app.

**Comment by davidyoondrums** [comment]
> Did your commit resolve the issue you were having @davidyoondrums?

I haven't extensively tested it but it seems to have resolved the issue.

**Comment by cybertunnel** [comment]
> > Did your commit resolve the issue you were having @davidyoondrums?
> 
> I haven't extensively tested it but it seems to have resolved the issue.

Thanks for the response, have you been able to test further? I have not been able to replicate the issue on my end, so wanted to ensure this fixes the described issue before pulling into the development branch.

**Comment by davidyoondrums** [comment]
I tested it and other have tested it also. I think are good to go!

**Comment by Ethenyl** [comment]
Thanks @davidyoondrums for the feedback. I'll merge the PR to integrate your fix unto the next release.

**Comment by Ethenyl** [comment]
Fixed by #113.
