### ISSUE TITLE
Splashbuddy Not Appearing Unless User logs In

### ISSUE THREAD

**Issue by blackberryhell** [Shufflepuck/SplashBuddy#123]
I am having an issue where my imaging policy kicks in at enrolment and installs splashbuddy but splashbuddy doesn't launch unless I login, is this expected behaviour?

**Comment by cybertunnel** [comment]
This is expected since it runs in user space, however there is a branch that does have where it runs in root space. Keep in mind, it running in root space is not a good idea since it could be a avenue for attack.

**Comment by blackberryhell** [comment]
Hi Tyler 

Thanks for getting back to me it’s appreciated.

Regards

Alex

**Comment by rypowell1988** [comment]
Hi @cybertunnel - can you point me in the direction of the branch where it does work at the login screen?  I'm having trouble tracking this down.

Thanks
Ryan

**Comment by cybertunnel** [comment]
@rypowell1988 sorry for the extreme delay, I didn't see this until just now. Did you find the login window branch of this?

**Comment by cybertunnel** [comment]
If you still need it, and/or someone else finds this issue; https://github.com/smithjw/SplashBuddy I believe is the one that works on the Login Window.
