### ISSUE TITLE
Updating the preference file io.fti.SplashBuddy.plist doesn't show new entry

### ISSUE THREAD

**Issue by built2order** [Shufflepuck/SplashBuddy#43]
I've updated the preference file io.fti.SplashBuddy.plist, copied the file into /Library/Preferences folder however only the three default elements show up when the app is launch. Even changing the description of an established item is not reflected in the app. Removing the preferences file leaves an empty installation window. I've attached a screenshot and plist file for your review.

OS: 10.12.3

<img width="227" alt="screen shot 2017-10-07 at 1 17 14 am" src="https://user-images.githubusercontent.com/6132811/31282129-4c73d8e4-aafd-11e7-9bd5-b967a97e1af3.png">

[io.fti.SplashBuddy.plist.txt](https://github.com/ftiff/SplashBuddy/files/1362946/io.fti.SplashBuddy.plist.txt)

**Comment by ftiff** [comment]
Thank @built2order this is not a bug but a « feature » 👍 

Seriously, the preferences are cached, so you need to `sudo killall -HUP cfprefsd` for SplashBuddy to pick the changes from the plist. Does it help?

**Comment by danielsjacobson** [comment]
Super good to know. Fixes my issues!
