### ISSUE TITLE
Feature Request: Add quit and don't reopen

### ISSUE THREAD

**Issue by n0brainer** [Shufflepuck/SplashBuddy#45]
For troubleshooting, it would be great to have a quit and do **not** reopen SB so I'm not scrambling to find the error in-between relaunches.

**Comment by ftiff** [comment]
Thanks for your feature request! 

You can already use CMD+ALT+CTRL+Q d91e62c22021c2616cc6db4f6ca37b923037c57e

I leave this request open to include it in the documentation!

**Comment by cybertunnel** [comment]
@ftiff did you add it to the documentation?
