### ISSUE TITLE
Allow auto refresh of webview

### ISSUE THREAD

**Issue by ftiff** [Shufflepuck/SplashBuddy#56]
Some MacAdmins parse the index.html to write dynamic information such as an IP Address
Feature Request would be to automatically refresh the webview every x seconds

**Comment by cybertunnel** [comment]
Could be a preference key

**Comment by cybertunnel** [comment]
To use this feature, you will need to set the `webRefreshRate` to a `Number` type with a value greater or equal to `1`. This setting is in seconds of delay between refreshes.
