### ISSUE TITLE
type-o in change notes for 1.2.0

### ISSUE THREAD

**Issue by n0brainer** [Shufflepuck/SplashBuddy#71]
/var/tmp/SplashBuddy/ with more tag files : CriticalDone (All critical softwares are installed), ErrorWhileInstalling (Errors while installing), AllInstalled (All software is installed (failed or success)), AllSuccessfullyInstalled (All software is sucessfully installed).

The folder is /private/tmp/SplashBuddy

Thank you to @xinput in slack to helping find it :)

**Comment by Ethenyl** [comment]
Fixed by #72.
