### ISSUE TITLE
Disable Full Screen

### ISSUE THREAD

**Issue by dinero1010** [Shufflepuck/SplashBuddy#78]
What is the most efficient way to disable the full screen mode and simply display the Splashbuddy screen?  Appreciate any help.

**Comment by HowardGMac** [comment]
What you are looking for is the hideBackground function so that the rest of your screen is not blocked out.  You can find information on that here: 
https://github.com/Shufflepuck/SplashBuddy/wiki/60---Options#hide-background-11

**Comment by smithjw** [comment]
Would there be enough inters to have this option enabled/disabled by a preference key?

**Comment by dinero1010** [comment]
Thanks all - i found the hide background function and its working well.  I would vote +1 for this option to be configurable via preference key... i know in our case, we leverage SplashBuddy as a 'Step 2' of our enrollment process and as such, the full screen is not required.

**Comment by dinero1010** [comment]
Yes, hideBackground was the option i was looking for.  Thank you for the help.

**Comment by Ethenyl** [comment]
Issue has been resolved, I'm closing it.
