### ISSUE TITLE
German localisation fixed

### ISSUE THREAD

**Issue by entusdictus** [Shufflepuck/SplashBuddy#81]
I've reworked the German SB localisation and updated strings and button labels. Button labels and wordings now match the German macOS locale. 

[German-localizable.strings.txt](https://github.com/Shufflepuck/SplashBuddy/files/1937674/German-localizable.strings.txt)

**Comment by Ethenyl** [comment]
Hi @entusdictus,

Glad to hear that you're working on the German translation. Do you want me to create a PR to integrate your change or are you going to do it?

**Comment by Ethenyl** [comment]
Localisation update will be implemented by #84.

**Comment by Ethenyl** [comment]
Will be available in the next version of **SplashBuddy**.
