### ISSUE TITLE
Spanish Localization

### ISSUE THREAD

**Issue by dinero1010** [Shufflepuck/SplashBuddy#85]
Hello - Would it be possible to the add Spanish (ES) localization to the base package?  Much appreciated!

**Comment by Ethenyl** [comment]
Hi @dinero1010,

It's totally possible to add Spanish localization, but we don't have any official translator to work on it.

So the first implementation might be based on Google translated strings.

**Comment by Ethenyl** [comment]
Hi @dinero1010,

The Spanish translation will be implemented by the PR #88.

Feel free to check the new localization strings and comment (on the PR if possible, otherwise here) if something seems weird. Better safe than sorry ;-)
