### ISSUE TITLE
CLose out Splash Buddy,  keeps reappearing

### ISSUE THREAD

**Issue by djtonyc77** [Shufflepuck/SplashBuddy#87]
I just tested the app and opened it,  I'm able to  use command, alt Q to quit, but keeps reopening.  I've rebooted in to safe mode, closed all apps, but when i reboot eventually splashbuddy keeps appearing.  I've deleted it from apps, the unzipped folder.  Any other instances where it may be hiding out.

**Comment by MatGriffin** [comment]
Library/Application Support/SplashBuddy/

**Comment by Ethenyl** [comment]
Marking issue as closed since it was resolved.
