### ISSUE TITLE
We are preparing your Mac...

### ISSUE THREAD

**Issue by danshaw** [Shufflepuck/SplashBuddy#93]
Would anyone have an idea why I might be stuck at the "We are preparing your Mac..." stage of SplashBuddy? I have removed all but one app, re-imaged multiple time, deleted the computer from JAMF, and I can't see to get passed this stage. The applications to get installed in the background from JAMF because of the "on enrollment" trigger, but SplashBuddy is not seeing it for some reason. 

I'm testing this on 10.13.5 running with JAMF Pro 10.5.

**Comment by cybertunnel** [comment]
make sure the name of the `.pkg` file maches the `packageName` in the preferences file. You can find the exact package name by doing `cat /var/log/jamf.log | grep .pkg` and look for the package that matches your application you are tracking for installation.
Ex: For a OneDrive package named `OneDrive-1.203.455`
Your plist might look like something like this - 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>applicationSideMenu</key>
	<true/>
	<key>continueAction</key>
	<string>Restart</string>
	<key>applicationsArray</key>
	<array>
                <dict>
			<key>canContinue</key>
			<true/>
			<key>description</key>
			<string>VPN Client</string>
			<key>displayName</key>
			<string>Pulse Secure</string>
			<key>iconRelativePath</key>
			<string>pulseSecure.png</string>
			<key>packageName</key>
			<string>PulseSecure</string>
		</dict>
        </array>
	<key>assetPath</key>
	<string>/Library/Application Support/SplashBuddy</string>
	<key>htmlPath</key>
	<string>presentation.html</string>
	<key>webRefreshRate</key>
	<integer>60</integer>
</dict>
</plist>
```

**Comment by MatGriffin** [comment]
One way I test is make the item available in self service, install from self service. The once I'e built my SB and set the prefs install it on the same Mac and if all correct it will go green as SB will pick it up from the JAMF log.

**Comment by danshaw** [comment]
Thanks for the help guys! @cybertunnel was right, I just didn't have the naming correct. Working like a charm now!
