### ISSUE TITLE
Hold off until user is logged into computer

### ISSUE THREAD

**Issue by danshaw** [Shufflepuck/SplashBuddy#95]
If I hang out on the setup screen for a couple of minutes (lets say the user walks away briefly), behind the scenes the computer is enrolling (DEP enabled). This causes splashbuddy and the "please wait" policy to fire off and start installing programs due to the trigger being "on enrollment". 

Is there any way to prevent this from happening until the user logs into the computer? I guess its not the end of the world that it starts, but there are some programs that look for the logged in user and when its on the setup screen that user is "_mbsetupuser".

![screenshot 2018-06-28 08 33 13](https://user-images.githubusercontent.com/6180024/42040895-f2edaad0-7aad-11e8-890b-8bd87edaed86.png)

**Comment by cybertunnel** [comment]
That is all based on your Jamf Pro workflow. You could add a script to the beginning of your workflow and then kick off the policies once a user is detected to be logged in.
