### ISSUE TITLE
Japanese Localization

### ISSUE THREAD

**Issue by taniguti** [Shufflepuck/SplashBuddy#96]
Hi, 

How about adding Japanese localization into the base package?
I've put Localizable.strings into japanese on my forked repository. 

Thanks.

**Comment by Ethenyl** [comment]
Hi Takanori,

I'll add the Japanese localization into the app based on your fork.

I guess the UI is not made for RTL but since it's pretty straightforward, and without long texts, it should behave nicely.

**Comment by Ethenyl** [comment]
Implemented by #97.
